# Generated by Django 3.0.6 on 2020-05-21 20:03

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dynos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RError',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('R14', 'R14'), ('R15', 'R15'), ('R99', 'R99')], default='R14', max_length=5)),
                ('least_count', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(1000)])),
                ('time_window', models.IntegerField(default=300, validators=[django.core.validators.MinValueValidator(60), django.core.validators.MaxValueValidator(3600)])),
                ('email_alert', models.BooleanField(default=False)),
                ('log', models.BooleanField(default=False)),
                ('action', models.CharField(choices=[('No Action', 'No Action'), ('Restart Dyno', 'Restart Dyno'), ('Restart App', 'Restart App')], default='No Action', max_length=15)),
                ('dyno_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dynos.Dyno')),
            ],
            options={
                'verbose_name': 'Rxx Error',
                'verbose_name_plural': 'Rxx Errors',
                'unique_together': {('dyno_fk', 'category')},
            },
        ),
        migrations.CreateModel(
            name='HError',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('H10', 'H10'), ('H12', 'H12'), ('H80', 'H80'), ('H99', 'H99')], default='H10', max_length=5)),
                ('least_count', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(1000)])),
                ('time_window', models.IntegerField(default=300, validators=[django.core.validators.MinValueValidator(60), django.core.validators.MaxValueValidator(3600)])),
                ('email_alert', models.BooleanField(default=False)),
                ('log', models.BooleanField(default=False)),
                ('action', models.CharField(choices=[('No Action', 'No Action'), ('Restart Dyno', 'Restart Dyno'), ('Restart App', 'Restart App')], default='No Action', max_length=15)),
                ('dyno_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dynos.Dyno')),
            ],
            options={
                'verbose_name': 'Hxx Error',
                'verbose_name_plural': 'Hxx Errors',
                'unique_together': {('dyno_fk', 'category')},
            },
        ),
    ]
